import type { Metadata } from "next";
import { Noto_Sans, Racing_Sans_One } from "next/font/google";
import "@/_styles/globals.css";

const notoSans = Noto_Sans({
  subsets: ["latin"],
});
const racingSans = Racing_Sans_One({
  variable: "--font-racing-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Swift Tool Hire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans} ${racingSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
